stages:
  - build

variables:
  API_IMAGE: harryphoebus/eduverse-api
api_build:
  stage: build
  image: docker:dind
  services:
    - docker:dind
  before_script:
    - echo "Building api"
    - cd api
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
  script:
    - docker build -t $API_IMAGE:latest .
    - docker push $API_IMAGE:latest
  only:
    - main #run when changes on main branch only
  tags:
    - gitlab-org-docker

